# Generated by Django 3.2 on 2021-04-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('meat', 'Meat'), ('fish', 'Fish'), ('veg', 'Vegetable'), ('grain', 'Grain'), ('fruit', 'Fruit'), ('spice', 'Spice'), ('seed', 'Seed'), ('dairy', 'Dairy')], max_length=100)),
                ('unit', models.CharField(choices=[('gram', 'Grams'), ('ml', 'Ml'), ('ltr', 'Ltr')], max_length=100)),
            ],
        ),
    ]
